# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: nuhi.nlite
PackageVersion: 1.4.9.3
InstallerType: inno
Installers:
- InstallerUrl: https://www.nliteos.com/download/nLite-1.4.9.3.setup.exe
  Architecture: x86
  InstallerSha256: 3854C1B6C60F2F4A2B07C824661EA518444004C115C04F19415F0429E5B11E08
ManifestType: installer
ManifestVersion: 1.5.0
