# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: nvaccess.osara
PackageVersion: 2023.1pre-1215,f200b322
PackageLocale: en-US
Publisher: NV Access Limited
PackageName: OSARA
License: GNU General Public License version 2.0
Copyright: Copyright (C) 2014-2023 NV Access Limited, James Teh & other contributors
ShortDescription: Open Source Accessibility for the REAPER Application
ManifestType: defaultLocale
ManifestVersion: 1.5.0
